# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["TEST_DB_NAME"] %>
  host: <%= ENV["TEST_DB_HOST"] %>
  port: <%= ENV["TEST_DB_PORT"] %>
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DB_NAME"] %>
  host: <%= ENV["TEST_DB_HOST"] %>
  port: <%= ENV["TEST_DB_PORT"] %>
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>

production:
  <<: *default
  database: production_to_do